### ISSUE TITLE
Improve software dependency accessibility (was: [Features] A script that install dependancies)

### ISSUE THREAD

**Issue by tr1p0p** [WoeUSB/WoeUSB#27]
Hi, i know linux it's hardcore, but i wonder : Why you don't make the install of the ONLY usb windows maker more easy ?

I mean, you don't even put some lines to copy/cut  in the terminal to install the dependencies in the readme, you make a list, and it's not even the name of the soft you can install with sudo apt for example.

So, why not make a like a script that install or a more accessible way of install this ?

Thanks a lot for the work !

**Comment by Lin-Buo-Ren** [comment]
> I mean, you don't even put some lines to copy/cut in the terminal to install the dependencies in the readme, you make a list, and it's not even the name of the soft you can install with sudo apt for example.

That would clutter the README with distro-specific information, which I'd currently prefer not to.  My plan is to add a link to the project's wiki where one should find/add distro-specific dependency details on the README.

> So, why not make a like a script that install or a more accessible way of install this ?

I would prefer improving the distribution packaging instead (#1, #3) so that one wouldn't need to care about the software dependencies in the first place.  Implement such scripts duplicates the functionality while adding the burden of maintaining a separate code filled with distro-specific and/or arch-specific details.

Let's stick with the documentation accessibility for now as it can be easily implemented.
