### ISSUE TITLE
Device always busy

### ISSUE THREAD

**Issue by unixandria-xda** [WoeUSB/WoeUSB#4]
WoeUSB always states the device is busy.

Which is hilarious because _none of the partitions are even mounted!_

Umount confirms the same.

Why is WoeUSB saying this and how can I resolve it?

Host system is Fedora 33

**Comment by Lin-Buo-Ren** [comment]
Please run the `woeusb` script with `bash -x` and paste the result here.

**Comment by unixandria-xda** [comment]
I'm running the gui version so what exact effect will that have?

**Comment by unixandria-xda** [comment]
CLI version gives: 
```
WoeUSB v@@WOEUSB_VERSION@@
==============================
Error: Target device is currently busy, unmount all mounted partitions in target device then try again
Target device is busy, please make sure you unmount all filesystems on target device or shutdown the computer before detaching it.
++ __vte_prompt_command
+++ HISTTIMEFORMAT=
+++ history 1
+++ sed 's/^ *[0-9]\+ *//'
++ local 'command=sudo woeusb --device Simply.Amazing.10.Pro.Insider.Preview.EN-US.x64.iso /dev/sda --tgt-fs NTFS'
++ command='sudo woeusb --device Simply.Amazing.10.Pro.Insider.Preview.EN-US.x64.iso /dev/sda --tgt-fs NTFS'
++ local 'pwd=~'
++ '[' /home/alexandria '!=' /home/alexandria ']'
++ pwd='~'
++ printf '\033]777;notify;Command completed;%s\033\\\033]777;precmd\033\\\033]0;%s@%s:%s\033\\' 'sudo woeusb --device Simply.Amazing.10.Pro.Insider.Preview.EN-US.x64.iso /dev/sda --tgt-fs NTFS' alexandria fedora '~'
++ __vte_osc7
+++ /usr/libexec/vte-urlencode-cwd
++ printf '\033]7;file://%s%s\033\' fedora /home/alexandria
```

**Comment by Lin-Buo-Ren** [comment]
Use the command: `sudo bash -x path/to/woeusb`

**Comment by cnsr** [comment]
Please check if the ISO you are trying to burn is mounted - I had a similar issue, and my ISO was mounted.

**Comment by Lin-Buo-Ren** [comment]
Hello, as @cnsr pointed out this is probably due to the filesystems on the target device being mounted (possible due to the system's automounting feature), refer [Why does WoeUSB can't find my external usb drive after I use the "eject" button in FileManager etc. to unmount its filesystems? - F.A.Q. · WoeUSB/WoeUSB Wiki](https://github.com/WoeUSB/WoeUSB/wiki/F.A.Q.#why-does-woeusb-cant-find-my-external-usb-drive-after-i-use-the-eject-button-in-filemanager-etc-to-unmount-its-filesystems) for additional info.
