### ISSUE TITLE
Focus of this project

### ISSUE THREAD

**Issue by flokoe** [WoeUSB/WoeUSB#79]
Hi there!

I didn't know where to put this, so I selected this repo as it seems the most popular.

As the Hacktoberfest started yesterday, I wanted to see if I could help, but I am confused about where to start.

I understand the migration from the original repo is complete and different repositories emerged:

- This repository (Bash, no frontend).
- [WoeUSB-frontend-wxgtk](https://github.com/WoeUSB/WoeUSB-frontend-wxgtk) (C ++, providing a frontend via wxGTK).
- [WoeUSB-ng](https://github.com/WoeUSB/WoeUSB-ng) (Python, providing a frontend via wxGTK).

It seems inefficient for an organization to maintain three different projects with the same goal but different code bases.

I like this project as it is the only one I can create working windows boot sticks on Linux, but I am concerned that this splitting slows down the progress. Therefore I want to start a discussion about the focus of this project.

I propose archiving the WoeUSB-frontend-wxgtk repo as it looks pretty abandoned and then direct focus on either the Bash or Python port.

Furthermore, it may be worth thinking about

- Whether Bash is the right language for such a complex program.
- Whether there is enough demand for a GUI front end.

I am happy to hear any thoughts on this.

Best regards
Florian

**Comment by unixquuw** [comment]
Imo, bash is the easiest language you can ever touch. Sure, the could use python or c++ but **why if bash is working good already?**. I also dont understand **why** someone would like a GUI front end. It's easy as just typing out fdisk -l and selecting your device, then typing out woeusb --device blah blah. 

So tl;dr
no need for GUI, bash is simple enough

[Best wishes]

**Comment by brlin-tw** [comment]
Hello, unfortunately, I am unable to respond throughout the October, but here it is:

> It seems inefficient for an organization to maintain three different projects with the same goal but different code bases.

One of the reasons to split the project into three independent ones is to be otherwise efficient for _all_ of them.  When the era where the Bash core implementation and the wxWidgets frontend shares the codebase I am unable to focus on improving the core without considering whether the change will break the frontend (which do have a great share of the userbase), splitting them allows each of them to go their own path, while making possible for one that depends on the other component's older version (like the wxWidgets frontend) to still ship the old version of their dependency(via version pinning, though this goal doesn't have much progress as of now).

> I am concerned that this splitting slows down the progress. Therefore I want to start a discussion about the focus of this project.

> I propose archiving the WoeUSB-frontend-wxgtk repo as it looks pretty abandoned and then direct focus on either the Bash or Python port.

The thing is that the point of "keep a single implementation will make the development faster" simply isn't valid.  People have different skills and interests and one simply can't throw all people together in a single project and hope that the development speed will magically multiply.

It _is_ fine to have multiple focuses in a project and let people choose which they are comfortable contributing.  If one doesn't like a focus they create a new focus, and possibly advance together while sharing part of the resources which is pretty much the lovely nature of free and open-source software.  In this exact sense, I am personally against the idea of archiving a sub-project which essentially means giving up the possibilities of a certain topic.

Maybe in the future there may be people who have the interest to bring life to the wxWidgets frontend, who knows? :shrug:

> Whether Bash is the right language for such a complex program.

I would say that the program is not really that complex as the simplicity of this application is the reason why I contributed to the project in the first place.

For the question of whether Bash is the right language, I would say that while it suffices to do the task I would say that it is not a perfect choice due to the following reasons:

* It has poor code reusability (it doesn't have a built-in library/package management facility and if [alternatives](https://bpkg.sh/) are not easy to incorporate one have to resort to implementing all the wheels)
* Language features to improve the readability/writability of the program requires recent Bash versions which as of now isn't available in some popular distributions (like CentOS 7)
* Other reasons that I am unable to recall as of now
