### ISSUE TITLE
woeusbgui no longer supported in Fedora!  Please change something!

### ISSUE THREAD

**Issue by ToddAndMargo** [WoeUSB/WoeUSB#94]
Fedora 35
WoeUSB-5.1.2-3.fc35.x86_64

Sometimes something work so well, there is no need for maintenance.  Woeusbgui would be an example.

As of Fedora 35, the Fedora repository has dropped woeusbgui, as it is "no longer maintained".  

https://bugzilla.redhat.com/show_bug.cgi?id=2027504#c5

This is a MAJOR loss of functionality!    AAAAA HHHHHH !!!!

Would you please do something, change the background color, ANYTHING, to woeusbgui to appease "the power that be" at Fedora so they will stick it back in the repo!

Many thanks,
-T

**Comment by brlin-tw** [comment]
The maintainer of the package is right, woeusbgui is dropped because no one is currently able to maintain it.  In the meantime, please check out [WoeUSB/WoeUSB-ng: WoeUSB-ng is a simple tool that enable you to create your own usb stick windows installer from an iso image or a real DVD. This is a rewrite of original WoeUSB.](https://github.com/WoeUSB/WoeUSB-ng) for an alternative.
